# Generated by Django 3.2 on 2022-06-22 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lastwill.swaps_common.orderbook.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deploy', '0001_initial'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapsMailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=None, max_length=50, null=True)),
                ('telegram_name', models.CharField(default=None, max_length=50, null=True)),
                ('name', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SwapsNotificationDefaults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=None, max_length=50, null=True)),
                ('telegram_name', models.CharField(default=None, max_length=50, null=True)),
                ('notification', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderBookSwaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=512, null=True)),
                ('memo_contract', models.CharField(default=lastwill.swaps_common.orderbook.models._get_memo, max_length=70, null=True)),
                ('contract_address', models.CharField(default='', max_length=255, verbose_name='Contract address')),
                ('base_address', models.CharField(default='', max_length=50, null=True)),
                ('base_limit', models.DecimalField(decimal_places=18, max_digits=50)),
                ('quote_address', models.CharField(default='', max_length=50, null=True)),
                ('quote_limit', models.DecimalField(decimal_places=18, max_digits=50)),
                ('owner_address', models.CharField(default='', max_length=50, null=True)),
                ('exchange_user', models.CharField(default='', max_length=512, null=True)),
                ('broker_fee', models.BooleanField(default=False)),
                ('broker_fee_address', models.CharField(default='', max_length=50, null=True)),
                ('broker_fee_base', models.FloatField(default=0, null=True)),
                ('broker_fee_quote', models.FloatField(default=0, null=True)),
                ('min_base_wei', models.CharField(default='', max_length=512, null=True)),
                ('min_quote_wei', models.CharField(default='', max_length=512, null=True)),
                ('base_amount_contributed', models.DecimalField(decimal_places=0, default=0, max_digits=78)),
                ('base_amount_total', models.DecimalField(decimal_places=0, default=0, max_digits=78)),
                ('quote_amount_contributed', models.DecimalField(decimal_places=0, default=0, max_digits=78)),
                ('quote_amount_total', models.DecimalField(decimal_places=0, default=0, max_digits=78)),
                ('public', models.BooleanField(default=True)),
                ('unique_link', models.CharField(default=lastwill.swaps_common.orderbook.models._get_unique_link, max_length=50, null=True, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('stop_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contract_state', models.CharField(choices=[('created', 'CREATED'), ('active', 'ACTIVE'), ('expired', 'EXPIRED'), ('postponed', 'POSTPONED'), ('done', 'DONE'), ('cancelled', 'CANCELLED'), ('hidden', 'HIDDEN')], default='created', max_length=63)),
                ('state', models.CharField(choices=[('created', 'CREATED'), ('active', 'ACTIVE'), ('expired', 'EXPIRED'), ('postponed', 'POSTPONED'), ('done', 'DONE'), ('cancelled', 'CANCELLED'), ('hidden', 'HIDDEN')], default='created', max_length=63)),
                ('state_changed_at', models.DateTimeField(auto_now_add=True)),
                ('whitelist', models.BooleanField(default=False)),
                ('whitelist_address', models.CharField(max_length=50, null=True)),
                ('is_exchange', models.BooleanField(default=False)),
                ('notification', models.BooleanField(default=False)),
                ('notification_email', models.CharField(default='', max_length=50, null=True)),
                ('notification_telegram_name', models.CharField(default='', max_length=50, null=True)),
                ('comment', models.TextField(default='')),
                ('is_rubic_order', models.BooleanField(default=False)),
                ('rubic_initialized', models.BooleanField(default=False)),
                ('is_displayed', models.BooleanField(default=True)),
                ('is_closed_by_limiter', models.BooleanField(default=False)),
                ('swaped_on_uniswap', models.BooleanField(default=False)),
                ('network', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='deploy.network')),
                ('swap_ether_contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='orderbookswaps',
            index=models.Index(fields=['id', 'unique_link'], name='swaps_commo_id_0140ec_idx'),
        ),
    ]
