# Generated by Django 3.2 on 2022-06-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinGeckoToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_title', models.CharField(max_length=255)),
                ('platform', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=150)),
                ('decimals', models.PositiveIntegerField(default=18)),
                ('source_image_link', models.URLField(blank=True, default='', max_length=512)),
                ('image_file', models.ImageField(blank=True, default='token_images/fa-empire.png', upload_to='token_images/')),
                ('rank', models.IntegerField(blank=True, default=0)),
                ('usd_price', models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_native', models.BooleanField(default=False)),
                ('is_displayed', models.BooleanField(default=True)),
                ('used_in_iframe', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'coingecko_tokens',
            },
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('token_name', models.CharField(max_length=512)),
                ('token_short_name', models.CharField(max_length=64)),
                ('decimals', models.IntegerField()),
                ('image_link', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='TokensUpdateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_time_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokensCoinMarketCap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_cmc_id', models.IntegerField(null=True)),
                ('token_name', models.CharField(max_length=512)),
                ('token_short_name', models.CharField(max_length=128)),
                ('token_platform', models.CharField(max_length=128, null=True)),
                ('token_address', models.CharField(max_length=128)),
                ('image_link', models.CharField(max_length=512)),
                ('token_rank', models.IntegerField(default=None, null=True)),
                ('image', models.ImageField(blank=True, default='token_images/fa-empire.png', upload_to='token_images/')),
                ('token_price', models.CharField(default=None, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_native', models.BooleanField(default=False)),
                ('is_displayed', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('token_name', 'token_short_name')},
            },
        ),
        migrations.AddIndex(
            model_name='coingeckotoken',
            index=models.Index(fields=['id'], name='coingecko_t_id_043c4a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coingeckotoken',
            unique_together={('short_title', 'address', 'platform')},
        ),
    ]
