# Generated by Django 3.2 on 2022-06-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fsym', models.CharField(max_length=50)),
                ('tsym', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('is_up_24h', models.BooleanField()),
                ('last_update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('fsym', 'tsym')},
            },
        ),
    ]
