# Generated by Django 3.2 on 2022-06-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotEOSRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eos_address', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=0, max_digits=78, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eth_address', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=0, max_digits=78, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TRONISHAirdropEOSISHHolders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=0, max_digits=78, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TRONISHAirdropWISHHolders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=0, max_digits=78, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TRONSnapshotEOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eos_address', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=0, max_digits=78, null=True)),
                ('tron_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TRONSnapshotEth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eth_address', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=0, max_digits=78, null=True)),
                ('tron_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TRONSnapshotTRON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tron_address', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=0, max_digits=78, null=True)),
            ],
        ),
    ]
