# Generated by Django 3.2 on 2022-06-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanamaTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('swap_rbc', 'Swap_rbc'), ('panama', 'Panama'), ('polygon', 'Polygon')], max_length=50, verbose_name='Type')),
                ('from_network', models.CharField(max_length=4, verbose_name='From network')),
                ('to_network', models.CharField(max_length=4, verbose_name='To network')),
                ('actual_from_amount', models.DecimalField(decimal_places=32, max_digits=50, verbose_name='Actual from amount')),
                ('actual_to_amount', models.DecimalField(decimal_places=32, max_digits=50, verbose_name='Actual to amount')),
                ('eth_symbol', models.CharField(max_length=42, verbose_name='ETH symbol')),
                ('bsc_symbol', models.CharField(max_length=42, verbose_name='BSC symbol')),
                ('update_time', models.DateTimeField(verbose_name='Update time')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('transaction_id', models.CharField(max_length=255, unique=True, verbose_name='Transaction id')),
                ('wallet_from_address', models.CharField(max_length=42, verbose_name='Wallet from address')),
                ('wallet_to_address', models.CharField(max_length=42, verbose_name='Wallet to address')),
                ('wallet_deposit_address', models.CharField(max_length=42, verbose_name='Wallet deposit address')),
                ('second_transaction_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Second transaction id')),
            ],
        ),
    ]
