# Generated by Django 3.2 on 2022-06-22 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default=None, max_length=35, null=True)),
                ('currencies', models.CharField(default=None, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSiteBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=78)),
                ('eth_address', models.CharField(default=None, max_length=50, null=True)),
                ('btc_address', models.CharField(default=None, max_length=50, null=True)),
                ('tron_address', models.CharField(default=None, max_length=50, null=True)),
                ('memo', models.CharField(default=None, max_length=25, null=True, unique=True)),
                ('subsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.subsite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=78)),
                ('eos_balance', models.DecimalField(decimal_places=0, default=0, max_digits=78)),
                ('internal_address', models.CharField(default=None, max_length=50, null=True)),
                ('internal_btc_address', models.CharField(default=None, max_length=50, null=True)),
                ('totp_key', models.CharField(default=None, max_length=16, null=True)),
                ('use_totp', models.BooleanField(default=False)),
                ('is_social', models.BooleanField(default=False)),
                ('lang', models.CharField(default='en', max_length=2)),
                ('last_used_totp', models.CharField(default=None, max_length=64, null=True)),
                ('memo', models.CharField(default=None, max_length=25, null=True, unique=True)),
                ('metamask_address', models.CharField(default=None, max_length=50, null=True)),
                ('is_swaps', models.BooleanField(default=False)),
                ('is_swaps_admin', models.BooleanField(default=False)),
                ('wish_bonus_received', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=36)),
                ('comment', models.CharField(default=None, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_accessed', models.DateTimeField(default=None, null=True)),
                ('swaps_exchange_domain', models.CharField(default=None, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'token')},
            },
        ),
    ]
